name: Windows Server 2025

on: 
  workflow_dispatch:
 
jobs:
  winserver2025:
    runs-on: ubuntu-22.04
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget -O loop.sh https://github.com/Efebey2903/Docker-VNC/raw/main/loop.sh
          wget -O docker-compose.yml https://github.com/Efebey2903/Docker-VNC/raw/main/winserv2025_compose.yml
          sleep 1
          docker-compose build
          sleep 2
          docker-compose up 
          cat compose
          sh loop.sh
